import React from 'react'

function Home() {
  return (

    
    React.createElement("div",{class :"wrapper"}, 
    React.createElement("div",{class:"table basic"},
    React.createElement("div",{class:"price-section"},
    React.createElement("div",{class:"price-area"},
    React.createElement("div",{class:"inner-area"},
    React.createElement("span",{class:"text"},"$"),
    React.createElement("span",{class:"price"},"15")))),
    React.createElement("div",{class:"package-name"}),
    React.createElement("div",{class:"features"},
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"One month free trail"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"100+ session view"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"Get bonus monthly"),
    React.createElement("span",{class:"icon cross"},
    React.createElement("i",{class:"far fa-times-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"Lifetime access"),
    React.createElement("span",{class:"icon cross"},
    React.createElement("i",{class:"far fa-times-circle"}))),
    React.createElement("div",{class:"btn"},
    React.createElement("button",null,"Purchace")))),
    
    React.createElement("div",{class:"table Premium"} ,
    React.createElement("div",{class:"price-section"},
    React.createElement("div",{class:"price-area"},
    React.createElement("div",{class:"inner-area"},
    React.createElement("span",{class:"text"},"$"),
    React.createElement("span",{class:"price"},"49")))),
    React.createElement("div",{class:"package-name"}),
    React.createElement("div",{class:"features"},
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"One month free trail"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"100+ session view"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"Get Bonus monthly"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"Lifetime Access"),
    React.createElement("span",{class:"icon cross"},
    React.createElement("i",{class:"far fa-times-circle"}))),
    React.createElement("div",{class:"btn"},
    React.createElement("button",null,"Purchace")))),
    
    React.createElement("div",{class:"table Ultimate"} ,
    React.createElement("div",{class:"price-section"},
    React.createElement("i",{class:"fa-solid fa-certificate fa-xl",id:"icon"}),
    React.createElement("div",{class:"price-area"},
    React.createElement("div",{class:"inner-area"},
    React.createElement("span",{class:"text"},"$"),
    React.createElement("span",{class:"price"},"99")))),
    React.createElement("div",{class:"package-name"}),
    React.createElement("div",{class:"features"},
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"One month free trail"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"100+ session view"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"Get Bonus monthly"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("li",null,React.createElement("span",{class:"list-name"},"Lifetime access"),
    React.createElement("span",{class:"icon check"},
    React.createElement("i",{class:"fas fa-check-circle"}))),
    React.createElement("div",{class:"btn"},
    React.createElement("button",null,"Purchace")))))
    
    );
}

export default Home